### ISSUE TITLE
Keep Weekly tag corresponding to commit hash for avoiding loss of image sha

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#103]
Currently, our workflows builds weekly tag based on cron schedule and pushes a [image-mirror of image built on openshift-ci](https://github.com/openshift/release/blob/c99e94e166a965532bae251e26b634ea33167395/ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a.yaml#L252). 

This pattern causes the image sha of the previous weekly tag to be orphan as the weekly tag move to the new image sha with the timeline. Causing users to use image sha of weekly tag face pull error with respect to weekly tag image.

**Acceptance critera**

- [ ] Change the workflow to use skopeo copy to create the weekly tag from latest commit hash

**Comment by atheo89** [comment]
This shall be fixed now.
Instead of using the weekly tag, we have removed it from the imagestream and now utilize the[ SHAs instead](https://github.com/opendatahub-io/odh-manifests/blob/master/notebook-images/base/params.env). 
Moreover, the update process is performed through the digest updater workflow, which uses the[ latest git commit](https://github.com/opendatahub-io/odh-manifests/blob/master/.github/workflows/notebooks-digest-updater-upstream.yaml#LL53C1-L53C107).
The leftovers from the weeklies into the CI can be removed through this [PR](https://github.com/openshift/release/pull/40327)

**Comment by atheo89** [comment]
Related PR for implementation has been merged
