### ISSUE TITLE
Remove thamos from requirements

### ISSUE THREAD

**Issue by KPostOffice** [opendatahub-io/notebooks#139]
`thamos` is causing the kubernetes client to be pinned at `~0.11`

**More Details**
Package `thamos` contains [requirement package](https://github.com/thoth-station/thamos/blob/602a343cd8ce986f476db4001f8e7bfc128e0539/Pipfile#L21) `thoth-common`
Which has a direct requirement dependency of [kubernetes to be pinned at `~0.11`](https://github.com/thoth-station/common/blob/47335e577ba8e0a29a0bac78addd27bb028a566c/Pipfile#L11)

**Comment by harshad16** [comment]
Got the ack for removing the `thamos` package.
Reference: https://redhat-internal.slack.com/archives/C03UA0RLSQM/p1690467770881809

**Comment by harshad16** [comment]
This issue is fixed, please use any of the following image or above:

- odh-minimal-notebook-image-n=quay.io/opendatahub/workbench-images@sha256:0f1fecf7b3ac9ccb9a6b68f36b98581226e6e97d0c17211cb168f60b31745627
- odh-minimal-gpu-notebook-image-n=quay.io/opendatahub/workbench-images@sha256:4dd963638bcbbb40f30bf6c57d5933771d02150be383d4f9f69942a11af2ee47
- odh-pytorch-gpu-notebook-image-n=quay.io/opendatahub/workbench-images@sha256:e3cc668afa83b277996d1c217ec7befc178f522843c8a67029e808719ce8dc95
- odh-generic-data-science-notebook-image-n=quay.io/opendatahub/workbench-images@sha256:2f3129c0b0847088b17c69677e48b8779e9db0a43c834f47689ac79cf03504c3
- odh-tensorflow-gpu-notebook-image-n=quay.io/opendatahub/workbench-images@sha256:8d13ff43413e121fd3b7c49920372b004d8dffa464acb39e0878b09292df132e
- odh-trustyai-notebook-image-n=quay.io/opendatahub/workbench-images@sha256:62ae9a028902bd5c4e04a1c9c568ed72551b99e30341247b50faa19e7bb98564
