### ISSUE TITLE
Include the tests in github workflow/ocp-ci

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#204]
With the Test framework and inclusion of the test notebook into the repo, we need to expand the unit testing to be executed on each PR.

Acceptance criteria:
- [x] [SPIKE]Explore the testing inclusion via GitHub workflow and OpenShift-CI. 
Find the time estimate of running it both.
- [x] Based on the command included in the makefile update the test in Openshift-CI.  
For example: [here](https://github.com/openshift/release/blob/6dbe5355c3d60899cf167398352af24f6702f609/ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml#L846)

**Comment by atheo89** [comment]
**Investigation (so far) in regards to the spike:** 

Here's a summary of the findings and the actions taken thus far:

GitHub workflow steps:
- **Filter out which image or images are affected by the PR**
Note: This was a missing part on the OpenShift CI workflow until implemented this bit: https://github.com/openshift/release/pull/43447 This integration helps us streamline the process and ensures that only necessary tests are executed.)
- **Build the corresponding image and its dependent ones**
- **Finally, run the test framework** 

Considerations:

The Openshift CI is an integral part of our flow of building and pushing the images to the registry. However, we've also realized that it offers the capability to implement unit tests. This means that we're currently running tests in both GitHub and OpenShift CI workflows. Given our goal of reducing test times, it's worth considering the following open item: [#11](https://github.com/opendatahub-io/notebooks/issues/11) 

We need to discuss whether it's necessary to duplicate tests in both GitHub and OpenShift CI, or if there's an opportunity to optimize this process and potentially reduce testing duplication. This could lead to more efficient testing and a quicker overall workflow.

Regarding the second part of this issue: _**Based on the command included in the makefile update the test in Openshift-CI**._
It's important to highlight its direct connection to the existing item outlined here: [#176](https://github.com/opendatahub-io/notebooks/issues/176). This linkage is significant because it pertains to the test framework already incorporated within the Makefile.

**Comment by harshad16** [comment]
Currently, the test of the notebooks is included via makefile.
as the test is already a part of the current e2e test.

Thanks for all the effort with this issue.
closing the issue.
