### ISSUE TITLE
Data science pipelines saved from the Elyra pipeline editor point to old runtimes

### ISSUE THREAD

**Issue by cfchase** [opendatahub-io/notebooks#218]
When I save a data science pipeline in the `.pipeline` format from the pipeline editor, it points to a runtime that only works with a certain version.  Next upgrade I get new runtime images and all my saved pipelines break.

**Comment by harshad16** [comment]
This is a problem, as the runtime image after the upgrade gets a new sha, and the old sha is dropped
causing users to re-pick the runtime image to function.
we will try to find a reasonable way to upgrade (as we won't have the changes frequently) or at least notify users that there is a change that could break users model.


Example: 
From Version RHODS 1.31 to 1.32,
we had a significant change. 
 -  We had moved from the curl-based pull of elytra-requirements.txt in runtime so that we can support users who don't have internet access.
 
 we need to publish this kinda information in the release notes.
 will plan with the documents team to get this kinda of information out.

**Comment by chtyler** [comment]
This has been added to the 1.33 release notes as a known issue. @harshad16, what are your thoughts on this text:

Data science pipelines saved from the Elyra pipeline editor reference a runtime no longer in use

When you save a data science pipeline in the Elyra pipeline editor with the format .pipeline, the pipeline references a runtime that is no longer in use. As a result, the pipeline fails to run after you next upgrade OpenShift Data Science.

**Comment by harshad16** [comment]
@chtyler , they wouldnt fail in all the time, only on some changes like rhods 1.31 -> <rhdos 1.32.

Perhaps, we should document it like this:

Data science pipelines saved from the Elyra pipeline editor reference a runtime no longer in use

When you save a data science pipeline in the Elyra pipeline editor with the format .pipeline in version on or before RHODS 1.31, the pipeline references a runtime that would not work in new releases that are above RHODS 1.32. 
As a result, the pipeline fails to run as it is, after you next upgrade OpenShift Data Science.
Re-selecting the runtime images, would fix the issue.

**Comment by harshad16** [comment]
@cfchase , can you share which version of RHODS, did you see this issue , please that would help us more

**Comment by jstourac** [comment]
Per discussion, I created appropriate issue for this in Jira project, see https://issues.redhat.com/browse/RHOAIENG-564.

**Comment by harshad16** [comment]
As mentioned on this comment: https://github.com/opendatahub-io/notebooks/issues/218#issuecomment-1730081181
and furthermore the project as moved ahead and other releases have ensured that old runtimes can be used by the users in any release. This issue is no longer a problem.

Closing this one, please feel free to create a new issue, if you notice a difference.
